#!/usr/bin/env node
// Builds an unsigned candidate; only the connected wallet can sign it.
import { ccc } from '@ckb-ccc/shell';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const addressString = process.argv[2];
if (!addressString?.startsWith('ckt1')) throw new Error('Usage: npm run deploy:prepare -- <testnet-address>');
const binary = await readFile(path.join(root, 'target/riscv64imac-unknown-none-elf/release/openswap-lock'));
const expected = JSON.parse(await readFile(path.join(root, 'docs/binary-identity.json'), 'utf8'));
const codeHash = ccc.hashCkb(binary);
if (codeHash !== expected.codeHash || createHash('sha256').update(binary).digest('hex') !== expected.sha256) {
  throw new Error('Binary differs from measured/tested candidate. Rerun validation and update the identity report.');
}
const GENESIS = '0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606';
const rpc = process.env.CKB_RPC_URL ?? 'https://testnet.ckb.dev';
const owned = ccc.ClientPublicTestnet.open({urls:[rpc]});
try {
  const client = owned.value;
  if ((await client.getHeaderByNumber(0))?.hash !== GENESIS) throw new Error('RPC is not CKB testnet');
  const address = await ccc.Address.fromString(addressString, client);
  const joy = await client.getKnownScript(ccc.KnownScript.JoyId);
  const secp = await client.getKnownScript(ccc.KnownScript.Secp256k1Blake160);
  const matches = (info) => address.script.codeHash === info.codeHash && address.script.hashType === info.hashType;
  const kind = matches(joy) ? ccc.KnownScript.JoyId : matches(secp) ? ccc.KnownScript.Secp256k1Blake160 : undefined;
  if (kind === undefined) throw new Error('Deployment preparation supports JoyID and secp addresses');
  class ReadOnlyFunder extends ccc.SignerDummy {
    constructor() { super(client, ccc.SignerType.CKB); }
    async getAddressObjs() { return [address]; }
    async getInternalAddress() { return addressString; }
    async prepareTransaction(txLike) {
      const tx = ccc.Transaction.from(txLike);
      await tx.addCellDepsOfKnownScripts(client, kind);
      const index = await tx.findInputIndexByLock(address.script, client);
      if (index !== undefined) {
        const witness = tx.getWitnessArgs(index) ?? ccc.WitnessArgs.from({});
        witness.lock = ccc.hexFrom(new Uint8Array(kind === ccc.KnownScript.JoyId ? 1000 : 65));
        tx.setWitnessArgs(index, witness);
      }
      return tx;
    }
  }
  const funder = new ReadOnlyFunder();
  const permanentLock = ccc.Script.from({codeHash:'0x'+'00'.repeat(32),hashType:'data1',args:'0x'});
  const data = ccc.hexFrom(binary);
  const tx = ccc.Transaction.from({outputs:[ccc.CellOutput.from({lock:permanentLock},data)],outputsData:[data]});
  await tx.completeInputsByCapacity(funder);
  await tx.completeFeeBy(funder);
  for (const input of tx.inputs) if (!await client.getCellLive(input.previousOutput,true)) throw new Error('Funding input is stale');
  const fee = await tx.getFee(client);
  if (fee < 0n || fee > ccc.fixedPointFrom('1')) throw new Error('Deployment fee exceeds 1 CKB ceiling');
  const dir = path.join(root,'deployments'); await mkdir(dir,{recursive:true});
  const summary = {network:'testnet',genesisHash:GENESIS,fundingAddress:addressString,rpc,
    ...expected,codeCellCapacity:tx.outputs[0].capacity.toString(),estimatedFee:fee.toString(),
    changeCapacity:tx.outputs.slice(1).reduce((sum,o)=>sum+o.capacity,0n).toString(),
    unsignedTxHash:tx.hash(),status:'unsigned',
    note:'JoyID master-key witness estimate. Connected wallet may add subkey proof/deps and recompute fees.'};
  await writeFile(path.join(dir,'testnet-candidate.json'),ccc.stringify(summary)+'\n');
  await writeFile(path.join(dir,'testnet-unsigned.json'),ccc.stringify(tx)+'\n');
  // The wallet rebuilds from the candidate inputs/outputs with its own preparation.
  // Remove provisional change so fee completion cannot accumulate change outputs.
  const initial = tx.clone(); initial.outputs = initial.outputs.slice(0,1); initial.outputsData = initial.outputsData.slice(0,1); initial.witnesses = [];
  const script = `// Generated by OpenSwap deploy-testnet.mjs. TESTNET ONLY.\nimport { ccc } from "@ckb-ccc/ccc";\nimport { render, signer, client } from "@ckb-ccc/playground";\n\nconst expectedAddress = ${JSON.stringify(addressString)};\nconst expectedHash = ${JSON.stringify(codeHash)};\nif (client.addressPrefix !== "ckt" || (await client.getHeaderByNumber(0))?.hash !== ${JSON.stringify(GENESIS)}) throw new Error("Select CKB TESTNET");\nconst owner = await ccc.Address.fromString(expectedAddress, client);\nif (!(await signer.getAddressObjs()).some(a => a.script.eq(owner.script))) throw new Error("Connect the specified funding wallet");\nconst tx = ccc.Transaction.from(${ccc.stringify(initial)});\nif (ccc.hashCkb(tx.outputsData[0]) !== expectedHash) throw new Error("Binary identity mismatch");\nawait render(tx);\nfor (const input of tx.inputs) if (!await client.getCellLive(input.previousOutput,true)) throw new Error("Stale funding input: regenerate deployment");\nawait tx.completeInputsByCapacity(signer);\nawait tx.completeFeeBy(signer);\nif (tx.outputs[0].lock.codeHash !== "0x"+"00".repeat(32) || tx.outputs[0].lock.hashType !== "data1" || tx.outputs[0].lock.args !== "0x" || tx.outputs[0].type || ccc.hashCkb(tx.outputsData[0]) !== expectedHash) throw new Error("Code output changed");\nfor (const output of tx.outputs.slice(1)) if (!output.lock.eq(owner.script) || output.type) throw new Error("Unexpected change destination");\nconst fee = await tx.getFee(client);\nif (fee < 0n || fee > ccc.fixedPointFrom("1")) throw new Error("Fee exceeds 1 CKB ceiling");\nconsole.log("Code storage (permanently locked testnet CKB):",ccc.fixedPointToString(tx.outputs[0].capacity));\nconsole.log("Network fee CKB:",ccc.fixedPointToString(fee));\nawait render(tx);\nconst txHash = await signer.sendTransaction(tx);\nconsole.log("DEPLOYMENT TX HASH:",txHash);\nawait client.waitTransaction(txHash,1);\nconsole.log("Committed. Record with: npm run deploy:record --",txHash);\n`;
  await writeFile(path.join(dir,'deploy-testnet.playground.ts'),script);
  console.log(JSON.stringify(summary,null,2));
} finally { await owned.dispose(); }
